---
- name: Install Prometheus Operator
  hosts: kube-master
  vars:
    promops_deploy:
      name: sa
      namespace: sa
      include_alertmanager: false
      monitor_k8s: false
      prometheus:
        nodeport: 31900
      grafana:
        nodeport: 31902
      spec:
        replicas: 1
      components:
        - grafana/grafana-credentials.yaml
        - grafana
        - prometheus
        - metrics-consumer
        - events-consumer
      service_monitors:
        - events
        - metrics
      storage:
        class_name: sa
        size: 2Gi
  tasks:
    - include_vars:
        file: dashboards.yml

    - import_role:
        name: redhat-nfvpe.prometheus-operator
        tasks_from: install.yml

    - include_playbook:
        name: elasticsearch.yml
