---
- name: Install Prometheus Operator
  hosts: kube-master
  vars:
    promops_deploy:
      name: sa
      namespace: sa
      include_alertmanager: false
      monitor_k8s: false
      prometheus:
        nodeport: 31900
      grafana:
        nodeport: 31902
      spec:
        replicas: 1
      components:
        - grafana/grafana-credentials.yaml
        - grafana
        - prometheus
        - metrics-consumer
        - events-consumer
      storage:
        class_name: sa
        size: 2Gi
  tasks:
    - include_vars:
        file: dashboards.yml

    - import_role:
        name: redhat-nfvpe.prometheus-operator
        tasks_from: install.yml

    - name: Clone ElasticSearch repo
      git:
        repo: https://github.com/pires/kubernetes-elasticsearch-cluster.git
        dest: "{{ ansible_env.HOME}}/elasticsearch"

    - name: (elasticsearch) create service
      command: >
        kubectl apply -n {{ promops_deploy.namespace }} -f es-discovery-svc.yaml -f es-svc.yaml -f es-master.yaml
      args:
        chdir: "{{ ansible_env.HOME }}/elasticsearch"

    - name: (elasticsearch) wait for master rollout to complete
      command: >
        kubectl -n {{ promops_deploy.namespace }} rollout status -f es-master.yaml
      args:
        chdir: "{{ ansible_env.HOME }}/elasticsearch"

    - name: (elasticsearch) create client
      command: >
        kubectl -n {{ promops_deploy.namespace }} apply -f es-client.yaml
      args:
        chdir: "{{ ansible_env.HOME }}/elasticsearch"

    - name: (elasticsearch) wait for client rollout to complete
      command: >
        kubectl -n {{ promops_deploy.namespace }} rollout status -f es-client.yaml
      args:
        chdir: "{{ ansible_env.HOME }}/elasticsearch"

    - name: (elasticsearch) setup data
      command: >
        kubectl -n {{ promops_deploy.namespace }} apply -f es-data.yaml
      args:
        chdir: "{{ ansible_env.HOME }}/elasticsearch"

    - name: (elasticsearch) wait for rollout of data
      command: >
        kubectl -n {{ promops_deploy.namespace }} rollout status -f es-data.yaml
      args:
        chdir: "{{ ansible_env.HOME }}/elasticsearch"
