---
qdr_dns_servers: 10.19.110.9 
qdr_image: tripleomaster/centos-binary-qdrouterd
qdr_image_tag: current-tripleo-rdo
qdr_kolla_config_files: /var/lib/kolla/config_files
qdr_config_data_puppet_generated: /var/lib/config-data/puppet-generated/qdrouterd

router:
    id_prefix: BAROMETER_ROUTER
    mode: interior

listeners:
    - host: 0.0.0.0
      port: 5673

connectors:
    - name: central-qdr
      role: inter-router
      host: blue.qdr-sa-telemetry.apps.nfvpe.site
      port: 20001
