---
qdr_dns_servers: 10.19.110.9
qdr_image: nfvpe/qpid-dispatch-router
qdr_image_tag: 1.2.0-2
qdr_root_config_path: /opt/sa/qdr.conf.d

router:
    id_prefix: BAROMETER_ROUTER
    mode: interior

listeners:
    - host: 0.0.0.0
      port: amqp

connectors:
    - name: central-qdr
      role: inter-router
      host: blue.qdr-sa-telemetry.apps.nfvpe.site
      port: 20001
