galaxy_info:
  author: NFVPE
  description: A role to install prerequisites for the Docker module
  company: Red Hat, Inc.

  license: Apache

  min_ansible_version: 2.6

  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags:
  - networking
  - packaging
  - system

dependencies: []
