---
- name: Get barometer-collect container image
  docker_image:
    name: "{{ collectd_image }}"
    tag: "{{ collectd_image_tag }}"

- name: Create directory for barometer-collectd configuration
  file:
    state: directory
    path: "{{ collectd_root_config_path }}"

- name: Deploy configuration for barometer-collectd on client
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ collectd_root_config_path }}/{{ item }}.conf"
  with_items:
    - default
    - amqp1
    - cpu
    - connectivity
    - procevent
    - sysevent

- name: Start barometer-collectd container
  docker_container:
    name: barometer
    image: "{{ collectd_image }}:{{ collectd_image_tag }}"
    privileged: yes
    network_mode: host
    entrypoint: /sbin/collectd -f -C /opt/collectd/etc/collectd.conf.d/
    volumes:
      - "{{ collectd_root_config_path }}/:/opt/collectd/etc/collectd.conf.d/"
      - /var/run:/var/run
      - /tmp:/tmp
    restart: yes
