---
router:
    id_prefix: BAROMETER_ROUTER
    mode: interior

listeners:
    - name: cloud-node
      host: 0.0.0.0
      port: 5673

connectors:
    - name: central-router
      role: inter-router
      host: blue.qdr-sa-telemetry.apps.nfvpe.site 
      port: 20001

collectd_host: 127.0.0.1
collectd_port: 5673
collectd_interval: 60
collectd_image: nfvpe/barometer-collectd
collectd_image_tag: latest
collectd_plugin_connectivity_interfaces:
  - eth0

plugins:
  - cpufreq
  - interface
  - disk
  - load
  - processes
  - uptime
  - df
  - memory
  - ovs_stats
  - ovs_events
  - hugepages
  - virt

collectd_plugin_ceph:
  - daemon: "osd.0"
    socketpath: "/var/run/ceph/ceph-osd.0.asok"
  - daemon: "osd.1"
    socketpath: "/var/run/ceph/ceph-osd.1.asok"
  - daemon: "mon.a"
    socketpath: "/var/run/ceph/ceph-mon.ceph1.asok"
  - daemon: "mds.a"
    socketpath: "/var/run/ceph/ceph-mds.ceph1.asok"
