---
router:
    id_prefix: COLLECTD_ROUTER
    mode: interior

listeners:
    - name: cloud-node
      host: 0.0.0.0
      port: 5673

connectors:
    - name: central-router
      role: inter-router
      host: 192.168.122.1
      port: 20001
