---
collectd_host: 172.17.0.1
collectd_port: 5666
collectd_interval: 1
collectd_kolla_config_files: /var/lib/kolla/config_files
collectd_config_data_puppet_generated: /var/lib/config-data/puppet-generated/collectd
collectd_image: docker.io/tripleomaster/centos-binary-collectd
collectd_image_tag: current-tripleo-rdo
collectd_plugin_virt_refreshinterval: 10
collectd_plugin_virt_hostnameformat: "hostname uuid"
collectd_plugin_virt_plugininstanceformat: name
collectd_plugin_virt_extrastats: "cpu_util disk disk_err domain_state pcpu fs_info job_stats_background perf vcpupin"

plugins:
  - cpu
  - cpufreq
  - df
  - disk
  - hugepages
  - interface
  - load
  - memory
  - processes
  - uptime
