---
- name: Install docker-py
  become: true
  become_user: root
  package:
    name: docker-python
    state: present

- name: Get QDR container image
  docker_image:
    name: "{{ item }}"
  with_items:
    - nfvpe/qpid-dispatch-router

- name: Create directory for QDR configuration
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/qdr.conf.d"

- name: Deploy configuration for QDR on client
  template:
    src: qdrouterd.conf.j2
    dest: "{{ ansible_env.HOME }}/qdr.conf.d/qdrouterd.conf"

- name: Start QDR container (cloud side)
  docker_container:
    name: qdr
    image: nfvpe/qpid-dispatch-router
    exposed_ports: 5672/tcp
    volumes: "{{ ansible_env.HOME }}/qdr.conf.d/:/etc/qdr.conf.d/:Z"
    restart: yes
    command: "--config=/etc/qdr.conf.d/qdrouterd.conf"
