---
- name: Get QDR container image
  docker_image:
    name: "{{ qdr_image }}"
    tag: "{{ qdr_image_tag }}"

- name: Create directory for QDR configuration
  file:
    state: directory
    path: "{{ qdr_root_config_path }}"

- name: Deploy configuration for QDR on client
  template:
    src: qdrouterd.conf.j2
    dest: "{{ qdr_root_config_path }}/qdrouterd.conf"

- name: Start QDR container (cloud side)
  docker_container:
    name: qdr
    image: "{{ qdr_image }}:{{ qdr_image_tag }}"
    exposed_ports: 5672/tcp
    volumes: "{{ qdr_root_config_path }}/:/etc/qdr.conf.d/:Z"
    dns_servers: "{{ qdr_dns_servers }}"
    network_mode: host
    pid_mode: host
    privileged: true
    restart: always
    command: "/sbin/qdrouterd --config=/etc/qdr.conf.d/qdrouterd.conf"
