---
- name: Get QDR container image
  docker_image:
    name: "{{ qdr_image }}"
    tag: "{{ qdr_image_tag }}"

- name: create persistent logs directory
  file:
    path: /var/log/container/qdrouterd
    state: directory

- name: make sure old-style persistent logs directory exists
  file:
    path: /var/log/qdrouterd
    state: directory

- name: Create directory for QDR configuration
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ qdr_config_files }}"

- name: Deploy configuration for QDR on client
  template:
    src: qdrouterd.conf.j2
    dest: "{{ qdr_config_files }}/qdrouterd.conf"

- name: Copy the certificate
  template:
    src: tls.crt.j2
    dest: "{{ qdr_config_files }}/tls.crt"

- name: Copy the key
  template:
    src: tls.key.j2
    dest: "{{ qdr_config_files }}/tls.key"

- name: Start QDR container (cloud side)
  docker_container:
    name: qdr
    image: "{{ qdr_image }}:{{ qdr_image_tag }}"
    exposed_ports: 5673/tcp
    volumes:
      - "{{ qdr_config_files }}:/tmp:ro"
      - /var/log/containers/qdrouterd:/var/log/qdrouterd:rw
      - /var/run/openvswitch:/var/run/openvswitch:ro
      - /var/run/ceph:/var/run/ceph:ro
      - /var/run/libvirt:/var/run/libvirt:ro
    dns_servers: "{{ qdr_dns_servers }}"
    network_mode: host
    pid_mode: host
    privileged: true
    restart_policy: unless-stopped
    user: root
