---
- name: Install requests python module via pip
  become: true
  become_user: root
  pip:
    name: requests
    version: 2.19.1
    state: present

- name: Install docker python module via pip
  become: true
  become_user: root
  pip:
    name: docker
    version: 3.5.0
    state: present

- name: Get QDR container image
  docker_image:
    name: "{{ qdr_image }}"
    tag: "{{ qdr_image_tag }}"

- name: Create directory for QDR configuration
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/qdr.conf.d"

- name: Deploy configuration for QDR on client
  template:
    src: qdrouterd.conf.j2
    dest: "{{ ansible_env.HOME }}/qdr.conf.d/qdrouterd.conf"

- name: Start QDR container (cloud side)
  docker_container:
    name: qdr
    image: "{{ qdr_image }}:{{ qdr_image_tag }}"
    exposed_ports: 5672/tcp
    volumes: "{{ ansible_env.HOME }}/qdr.conf.d/:/etc/qdr.conf.d/:Z"
    dns_servers: "{{ qdr_dns_servers }}"
    network_mode: host
    restart: yes
    command: "/sbin/qdrouterd --config=/etc/qdr.conf.d/qdrouterd.conf"
