---
- name: Install EPEL repository on CentOS (not RHEL)
  package:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'

- name: Enable a RHSM repository
  rhsm_repository:
    name: rhel-7-server-extras-rpms
    state: enabled
  when: ansible_distribution == 'RedHat'
  ignore_errors: true

- name: Install package dependencies
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-python
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
