---
- name: Install EPEL repository on CentOS and RHEL
  package:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install package dependencies
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python-pip
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install requests python module via pip
  pip:
    name: requests
    version: 2.19.1
    state: present

- name: Install docker python module via pip
  pip:
    name: docker
    version: 3.5.0
    state: present
