---
- name: Get barometer-collect container image
  docker_image:
    name: "{{ barometer_image }}"
    tag: "{{ barometer_image_tag }}"

- name: Create directory for barometer-collectd configuration
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/barometer-collectd.conf.d"

- name: Deploy configuration for barometer-collectd on client
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ ansible_env.HOME }}/barometer-collectd.conf.d/{{ item }}.conf"
  with_items:
    - default
    - amqp1
    - cpu
    - connectivity
    - procevent
    - sysevent

- name: Start barometer-collectd container
  docker_container:
    name: barometer
    image: "{{ barometer_image }}:{{ barometer_image_tag }}"
    privileged: yes
    network_mode: host
    entrypoint: /sbin/collectd -f -C /opt/collectd/etc/collectd.conf.d/
    volumes:
      - "{{ ansible_env.HOME }}/barometer-collectd.conf.d/:/opt/collectd/etc/collectd.conf.d/"
      - /var/run:/var/run
      - /tmp:/tmp
    restart: yes
